
[package]
name = "elic"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
serde = ["dep:serde"]

[dependencies]
roots = "0.0.8"
serde = { workspace = true, optional = true, features = ["derive"] }